/*
Package paseto provides an implementation for "Platform-Agnostic Security Tokens".

Platform-Agnostic Security Tokens (PASETO) provide a cryptographically secure,
compact, and URL-safe representation of claims that may be transferred between
two parties. The claims are encoded in JavaScript Object Notation (JSON),
version-tagged, and either encrypted using shared-key cryptography or signed
using public-key cryptography.

The key difference between PASETO and the JOSE family of standards (JWS [RFC7516],
JWE [RFC7517], JWK [RFC7518], JWA [RFC7518], and JWT [RFC7519]) is that JOSE allows
implementors and users to mix and match their own choice of cryptographic algorithms
(specified by the "alg" header in JWT), while PASETO has clearly defined protocol
versions to prevent unsafe configurations from being selected.

# Format

PASETO credentials consist of three or four segments, separated by a period (the
ASCII character whose number, represented in hexadecimal, is `2E`).

Without the Optional Footer:

	version.purpose.payload

With the Optional Footer:

	version.purpose.payload.footer

# Claims

The main segment of the token is the payload, which contains the available claims.
Claims are statements about an entity (typically, the PASETO holder) and additional
data. There are three types of claims: registered, public, and private.

Registered claims are a set of predefined claims which are not mandatory but recommended,
to provide a set of useful, interoperable fields.

Public claims can be defined at will, but to avoid collisions they should be registered
in the IANA JSON Web Token Registry or be defined as a URI that contains a collision
resistant namespace.

Private claims are the custom claims created to share information between parties that
agree on using them and are neither registered or public claims.

# Usage

The package focuses on providing a complete, robust and flexible implementation of the
PASETO specification. Some of the highlights include:
  - Create and validate all supported token types in the specification.
  - Tokens can be created using JSON template, facilitating API integration.
  - Easily generate new cryptographic keys for all token types, or import your own.
  - Access any custom contents encoded in the payload or footer segments of a token.
  - Easily validate all the standard registered claims defined in the specification.
  - Support for custom validations, allowing integrators to easily validate a token
    based on any custom contents.

The main component for token creation and validation is a 'Generator' instance. Once a
generator is initialized it uses 'TokenParameters' to create new signed or encrypted
tokens. A token instance can then be used through several methods provided by the type,
for example to obtain a compact textual representation of it.

To generate digitally signed tokens a provider instance must register the required
cryptographic keys, either when creating the instance of dynamically using the 'AddKey'
method.

	// (Error checks omitted for brevity)
	// Create a new generator and cryptographic keys.
	gen := NewGenerator("my-service.com")
	k1, _ := NewKey("key-1", V1L)
	k2, _ := NewKey("key-2", V1P)
	k3, _ := NewKey("key-3", V2P)
	_ = gen.AddKey(k1, k2, k3)

	// Prepare a token request. Requests can for example be received in JSON format from
	// a different service or API.
	req := &TokenParameters{
		Version:              "v2",
		Purpose:              pPublic,
		Audience:             []string{"consumer-service.com"},
		Subject:              "my-user",               // Specify any value useful for your context
		UniqueIdentifier:     "",                      // A random UUID will be generated by default
		NotBefore:            "0s",                    // Will be valid immediately after creation
		Expiration:           "48h",                   // Will be valid for 2 days
		UseUTC:               true,                    // Dates will be set as UTC zone
		AuthenticationMethod: []string{"pin", "face"}, // AMR codes from RFC-8176 are supported
		CustomClaims: customPayload{
			Foo: "bar", // Payload can include any additional data required
		},
		Footer: customFooter{
			Dimension: "c137", // Footer can include any additional data required
		},
	}

	// Generate a new token based on the provided. Token instances implement
	// "Stringer" to easily use as text.
	token, _ := gen.Issue(k3.ID(), req)
	fmt.Println(token)

	// Additionally, the token instance API facilitate inspection and common tasks.
	fmt.Printf("version: %s\n", token.Version())
	fmt.Printf("purpose: %s\n", token.Purpose())
	fmt.Printf("footer: %s\n", token.Footer())

	// You can easily decode contents in the payload and footer to any generic or custom type.
	ftr := customFooter{}           // Custom type
	pld := map[string]interface{}{} // Generic map; registered claims will also be included
	_ = token.DecodeFooter(&ftr)
	_ = token.DecodePayload(&pld)
	fmt.Printf("custom footer value: %s\n", ftr.Dimension)
	fmt.Printf("payload: %+v\n", pld)

	// Commonly used validators (aud, jti, sub, amr, exp, nbf, iat) can be generated from a
	// `TokenParameters` instance.
	checks := req.GetChecks()

	// You can also provide you own custom validators.
	checks = append(checks, func(token *Token) error {
		// Decode and validate my custom contents
		pld := customPayload{}
		if err := token.DecodePayload(&pld); err != nil {
			return err
		}
		if pld.Foo != "bar" {
			return errors.New("invalid bar value")
		}
		return nil
	})

	// You can validate a token instance directly.
	if err := token.Validate(checks...); err != nil {
		fmt.Printf("invalid token: %s", err)
	}

	// Or you can validate it as a string using the generator instance. Validating the token using the
	// generator instance will also verify the signature, encryption and "iss" registered claim.
	if err := gen.Validate(token.String(), checks...); err != nil {
		fmt.Printf("invalid token: %s", err)
	}

For more information:
https://tools.ietf.org/html/draft-paragon-paseto-rfc-00
*/
package paseto
