// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             buf-v1.56.0
// source: sample/v1/foo_api.proto

package samplev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FooAPI_Ping_FullMethodName             = "/sample.v1.FooAPI/Ping"
	FooAPI_Health_FullMethodName           = "/sample.v1.FooAPI/Health"
	FooAPI_Request_FullMethodName          = "/sample.v1.FooAPI/Request"
	FooAPI_Faulty_FullMethodName           = "/sample.v1.FooAPI/Faulty"
	FooAPI_Slow_FullMethodName             = "/sample.v1.FooAPI/Slow"
	FooAPI_OpenServerStream_FullMethodName = "/sample.v1.FooAPI/OpenServerStream"
	FooAPI_OpenClientStream_FullMethodName = "/sample.v1.FooAPI/OpenClientStream"
)

// FooAPIClient is the client API for FooAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sample "foo" service server.
type FooAPIClient interface {
	// Reachability test.
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pong, error)
	// Health test.
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Sample request.
	Request(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error)
	// Returns an error roughly about 20% of the time.
	Faulty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DummyResponse, error)
	// Exhibit a random latency between 10 and 200ms.
	Slow(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DummyResponse, error)
	// Sample server stream request.
	OpenServerStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenericStreamChunk], error)
	// Sample client stream request.
	OpenClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[OpenClientStreamRequest, StreamResult], error)
}

type fooAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFooAPIClient(cc grpc.ClientConnInterface) FooAPIClient {
	return &fooAPIClient{cc}
}

func (c *fooAPIClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, FooAPI_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooAPIClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FooAPI_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooAPIClient) Request(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FooAPI_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooAPIClient) Faulty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DummyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DummyResponse)
	err := c.cc.Invoke(ctx, FooAPI_Faulty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooAPIClient) Slow(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DummyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DummyResponse)
	err := c.cc.Invoke(ctx, FooAPI_Slow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooAPIClient) OpenServerStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenericStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FooAPI_ServiceDesc.Streams[0], FooAPI_OpenServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GenericStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooAPI_OpenServerStreamClient = grpc.ServerStreamingClient[GenericStreamChunk]

func (c *fooAPIClient) OpenClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[OpenClientStreamRequest, StreamResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FooAPI_ServiceDesc.Streams[1], FooAPI_OpenClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenClientStreamRequest, StreamResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooAPI_OpenClientStreamClient = grpc.ClientStreamingClient[OpenClientStreamRequest, StreamResult]

// FooAPIServer is the server API for FooAPI service.
// All implementations must embed UnimplementedFooAPIServer
// for forward compatibility.
//
// Sample "foo" service server.
type FooAPIServer interface {
	// Reachability test.
	Ping(context.Context, *emptypb.Empty) (*Pong, error)
	// Health test.
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	// Sample request.
	Request(context.Context, *emptypb.Empty) (*Response, error)
	// Returns an error roughly about 20% of the time.
	Faulty(context.Context, *emptypb.Empty) (*DummyResponse, error)
	// Exhibit a random latency between 10 and 200ms.
	Slow(context.Context, *emptypb.Empty) (*DummyResponse, error)
	// Sample server stream request.
	OpenServerStream(*emptypb.Empty, grpc.ServerStreamingServer[GenericStreamChunk]) error
	// Sample client stream request.
	OpenClientStream(grpc.ClientStreamingServer[OpenClientStreamRequest, StreamResult]) error
	mustEmbedUnimplementedFooAPIServer()
}

// UnimplementedFooAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFooAPIServer struct{}

func (UnimplementedFooAPIServer) Ping(context.Context, *emptypb.Empty) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFooAPIServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFooAPIServer) Request(context.Context, *emptypb.Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedFooAPIServer) Faulty(context.Context, *emptypb.Empty) (*DummyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Faulty not implemented")
}
func (UnimplementedFooAPIServer) Slow(context.Context, *emptypb.Empty) (*DummyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Slow not implemented")
}
func (UnimplementedFooAPIServer) OpenServerStream(*emptypb.Empty, grpc.ServerStreamingServer[GenericStreamChunk]) error {
	return status.Errorf(codes.Unimplemented, "method OpenServerStream not implemented")
}
func (UnimplementedFooAPIServer) OpenClientStream(grpc.ClientStreamingServer[OpenClientStreamRequest, StreamResult]) error {
	return status.Errorf(codes.Unimplemented, "method OpenClientStream not implemented")
}
func (UnimplementedFooAPIServer) mustEmbedUnimplementedFooAPIServer() {}
func (UnimplementedFooAPIServer) testEmbeddedByValue()                {}

// UnsafeFooAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooAPIServer will
// result in compilation errors.
type UnsafeFooAPIServer interface {
	mustEmbedUnimplementedFooAPIServer()
}

func RegisterFooAPIServer(s grpc.ServiceRegistrar, srv FooAPIServer) {
	// If the following call pancis, it indicates UnimplementedFooAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FooAPI_ServiceDesc, srv)
}

func _FooAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooAPI_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooAPI_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).Request(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooAPI_Faulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).Faulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_Faulty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).Faulty(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooAPI_Slow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).Slow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_Slow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).Slow(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooAPI_OpenServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FooAPIServer).OpenServerStream(m, &grpc.GenericServerStream[emptypb.Empty, GenericStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooAPI_OpenServerStreamServer = grpc.ServerStreamingServer[GenericStreamChunk]

func _FooAPI_OpenClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FooAPIServer).OpenClientStream(&grpc.GenericServerStream[OpenClientStreamRequest, StreamResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooAPI_OpenClientStreamServer = grpc.ClientStreamingServer[OpenClientStreamRequest, StreamResult]

// FooAPI_ServiceDesc is the grpc.ServiceDesc for FooAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FooAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample.v1.FooAPI",
	HandlerType: (*FooAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FooAPI_Ping_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FooAPI_Health_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _FooAPI_Request_Handler,
		},
		{
			MethodName: "Faulty",
			Handler:    _FooAPI_Faulty_Handler,
		},
		{
			MethodName: "Slow",
			Handler:    _FooAPI_Slow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenServerStream",
			Handler:       _FooAPI_OpenServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenClientStream",
			Handler:       _FooAPI_OpenClientStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sample/v1/foo_api.proto",
}
