// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sample/v1/foo_api.proto

package samplev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on GenericStreamChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GenericStreamChunk) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Sender

	// no validation rules for Stamp

	return nil
}

// GenericStreamChunkValidationError is the validation error returned by
// GenericStreamChunk.Validate if the designated constraints aren't met.
type GenericStreamChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenericStreamChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenericStreamChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenericStreamChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenericStreamChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenericStreamChunkValidationError) ErrorName() string {
	return "GenericStreamChunkValidationError"
}

// Error satisfies the builtin error interface
func (e GenericStreamChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenericStreamChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenericStreamChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenericStreamChunkValidationError{}

// Validate checks the field values on OpenClientStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *OpenClientStreamRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Sender

	// no validation rules for Stamp

	return nil
}

// OpenClientStreamRequestValidationError is the validation error returned by
// OpenClientStreamRequest.Validate if the designated constraints aren't met.
type OpenClientStreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OpenClientStreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OpenClientStreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OpenClientStreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OpenClientStreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OpenClientStreamRequestValidationError) ErrorName() string {
	return "OpenClientStreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e OpenClientStreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpenClientStreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OpenClientStreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OpenClientStreamRequestValidationError{}

// Validate checks the field values on StreamResult with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *StreamResult) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Received

	return nil
}

// StreamResultValidationError is the validation error returned by
// StreamResult.Validate if the designated constraints aren't met.
type StreamResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamResultValidationError) ErrorName() string { return "StreamResultValidationError" }

// Error satisfies the builtin error interface
func (e StreamResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamResultValidationError{}
