// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sample/v1/foo_api.proto

package samplev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenericStreamChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenericStreamChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenericStreamChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenericStreamChunkMultiError, or nil if none found.
func (m *GenericStreamChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *GenericStreamChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sender

	// no validation rules for Stamp

	if len(errors) > 0 {
		return GenericStreamChunkMultiError(errors)
	}

	return nil
}

// GenericStreamChunkMultiError is an error wrapping multiple validation errors
// returned by GenericStreamChunk.ValidateAll() if the designated constraints
// aren't met.
type GenericStreamChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenericStreamChunkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenericStreamChunkMultiError) AllErrors() []error { return m }

// GenericStreamChunkValidationError is the validation error returned by
// GenericStreamChunk.Validate if the designated constraints aren't met.
type GenericStreamChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenericStreamChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenericStreamChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenericStreamChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenericStreamChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenericStreamChunkValidationError) ErrorName() string {
	return "GenericStreamChunkValidationError"
}

// Error satisfies the builtin error interface
func (e GenericStreamChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenericStreamChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenericStreamChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenericStreamChunkValidationError{}

// Validate checks the field values on OpenClientStreamRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OpenClientStreamRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OpenClientStreamRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OpenClientStreamRequestMultiError, or nil if none found.
func (m *OpenClientStreamRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OpenClientStreamRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sender

	// no validation rules for Stamp

	if len(errors) > 0 {
		return OpenClientStreamRequestMultiError(errors)
	}

	return nil
}

// OpenClientStreamRequestMultiError is an error wrapping multiple validation
// errors returned by OpenClientStreamRequest.ValidateAll() if the designated
// constraints aren't met.
type OpenClientStreamRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OpenClientStreamRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OpenClientStreamRequestMultiError) AllErrors() []error { return m }

// OpenClientStreamRequestValidationError is the validation error returned by
// OpenClientStreamRequest.Validate if the designated constraints aren't met.
type OpenClientStreamRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OpenClientStreamRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OpenClientStreamRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OpenClientStreamRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OpenClientStreamRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OpenClientStreamRequestValidationError) ErrorName() string {
	return "OpenClientStreamRequestValidationError"
}

// Error satisfies the builtin error interface
func (e OpenClientStreamRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOpenClientStreamRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OpenClientStreamRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OpenClientStreamRequestValidationError{}

// Validate checks the field values on StreamResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StreamResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StreamResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StreamResultMultiError, or
// nil if none found.
func (m *StreamResult) ValidateAll() error {
	return m.validate(true)
}

func (m *StreamResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Received

	if len(errors) > 0 {
		return StreamResultMultiError(errors)
	}

	return nil
}

// StreamResultMultiError is an error wrapping multiple validation errors
// returned by StreamResult.ValidateAll() if the designated constraints aren't met.
type StreamResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StreamResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StreamResultMultiError) AllErrors() []error { return m }

// StreamResultValidationError is the validation error returned by
// StreamResult.Validate if the designated constraints aren't met.
type StreamResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamResultValidationError) ErrorName() string { return "StreamResultValidationError" }

// Error satisfies the builtin error interface
func (e StreamResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamResultValidationError{}
