// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddPetOperation     OperationName = "AddPet"
	DeletePetOperation  OperationName = "DeletePet"
	GetPetByIdOperation OperationName = "GetPetById"
	UpdatePetOperation  OperationName = "UpdatePet"
)
